
languages:
  fr:
    languageCode: "fr"
    languageName: "Français"
    title: "Accueil"
    weight: 1
  # en:
  #   languageCode: "en"
  #   languageName: "English"
  #   title: "Home"
  #   weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

enableEmoji: true

params:

  features:
    notes:
      enable: false

    flags:
      enable: true

    math:
      enable: true
      services:
        # https://katex.org/docs/autorender.html#api for more configurations
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: \\\[
              right: \\\]
              display: true
            - left: $
              right: $
              display: false
            - left: \\\(
              right: \\\)
              display: false
